// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stones.Data;

#nullable disable

namespace Stone1234.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250516111329_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stones.Models.Utilisateur", b =>
                {
                    b.Property<string>("IdUtilisateur")
                        .HasColumnType("text")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_complet");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("utilisateur", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
